services:
  monochrome-streamer:
    image: judeah666/monochrome-streamer:latest
    container_name: Monochrome-Streamer
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      APP_TITLE: Monochrome-Streamer
      DATA_DIR: /data
      SCAN_METADATA: tags
      SCAN_DURATIONS: "false"
      AUTO_SCAN_ON_START: "false"
    volumes:
      - /path/to/your/music:/music:ro
      - /opt/monochrome-streamer/data:/data
