import { DEFAULT_SETTINGS } from './constants.js';

export function createInitialState() {
  return {
    title: 'Monochrome-Streamer',
    generatedAt: null,
    albums: [],
    tracks: [],
    trackMap: new Map(),
    albumMap: new Map(),
    albumTracksMap: new Map(),
    artistGroups: [],
    artistGroupMap: new Map(),
    libraryFolders: { available: [], selected: [], scan: null },
    libraryPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    collectionFoldersPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    collectionPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    wishlistPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    artistPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    trackPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    libraryTrackResults: [],
    libraryTotals: { albums: 0, tracks: 0 },
    folderCache: new Map(),
    folderLoading: new Set(),
    homeAlbumIds: [],
    collectionAlbums: [],
    collectionAlbumsLoaded: false,
    collectionAlbumsLoading: false,
    collectionAlbumsLoadingPath: '',
    collectionAlbumsFetchId: 0,
    collectionFolders: [],
    collectionFoldersLoaded: false,
    collectionFoldersLoading: false,
    collectionFoldersError: '',
    collectionFoldersFetchId: 0,
    selectedCollectionFolderPath: '',
    wishlistAlbums: [],
    wishlistAlbumsLoaded: false,
    searchTerm: '',
    searchInputValue: '',
    searchFocusNonce: 0,
    alphabetFilter: 'all',
    mediaTypeFilters: new Set(),
    browseView: 'home',
    route: { view: 'home', albumId: null },
    currentTrackId: null,
    queueIds: [],
    shuffledQueueIds: [],
    shuffleActive: false,
    repeatMode: 'off',
    volume: 0.7,
    lastVolume: 0.7,
    queueOpen: false,
    fullscreenReturnHash: '',
    fullscreenLyricsHidden: false,
    fullscreenUiHidden: false,
    favoriteTrackIds: new Set(),
    favoriteAlbumIds: new Set(),
    libraryTab: 'albums',
    settingsTab: 'appearance',
    settingsStatusMessage: '',
    settings: { ...DEFAULT_SETTINGS },
    currentUser: null,
    canDownload: true,
    loginRouteOnly: false,
    pendingLibraryFolders: null,
    expandedFolderPaths: new Set(),
    selectedPlaylistId: 'favorites-tracks',
    artistInfoMap: new Map(),
    artistInfoLoading: new Set(),
    lyricsMap: new Map(),
    lyricsLoading: new Set(),
    lyricsRefreshRequestedIds: new Set(),
    tagEditorAlbumId: null,
    tagEditorMode: 'edit',
    tagEditorMusicBrainzId: '',
    tagEditorSuggestions: [],
    artistEditorName: '',
    lyricsEditorTrackId: '',
    lyricsSuggestions: [],
    visualizerActive: true,
    lyricsFrameId: 0,
    lastPlaybackPersistedAt: 0,
    audioContext: null,
    audioSource: null,
    analyser: null,
    analyserData: null,
    visualizerFrameId: 0,
    scanPollId: null,
    scanPollInFlight: false,
    searchFetchId: 0,
    searchDebounceId: 0,
    artistFetchId: 0,
    widgetSettings: null,
    ambientCoverUrl: '',
    ambientCoverTitle: '',
    ambientCoverArtist: '',
    ambientCovers: [],
  };
}
