import { DEFAULT_SETTINGS } from './constants.js';

export function createInitialState() {
  return {
    title: 'Monochrome-Streamer',
    generatedAt: null,
    albums: [],
    tracks: [],
    trackMap: new Map(),
    albumMap: new Map(),
    albumTracksMap: new Map(),
    albumTrackHydrationAttempts: new Set(),
    albumTrackHydrationInFlight: new Set(),
    artistGroups: [],
    artistGroupMap: new Map(),
    artistLibraryRequests: new Map(),
    artistLibraryCacheGeneration: 0,
    libraryFolders: { available: [], selected: [], scan: null },
    libraryPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    libraryPageQueryKey: '',
    libraryPageLoading: false,
    libraryPageLoadingKey: '',
    libraryPageCache: new Map(),
    libraryPagePrefetches: new Map(),
    libraryPageCacheGeneration: 0,
    browsePageCache: new Map(),
    browsePageRequests: new Map(),
    browsePageCacheGeneration: 0,
    collectionFoldersPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    collectionPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    wishlistPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    artistPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    trackPage: { limit: 50, offset: 0, total: 0, hasNext: false, hasPrevious: false },
    libraryTrackResults: [],
    libraryTotals: { albums: 0, tracks: 0 },
    folderCache: new Map(),
    folderRequests: new Map(),
    folderLoading: new Set(),
    folderCacheGeneration: 0,
    homeAlbumIds: [],
    homeAlbumCacheKey: '',
    homeAlbumRequest: null,
    homeAlbumRequestKey: '',
    recentlyAddedAlbumIds: [],
    recentlyAddedAlbumCacheKey: '',
    recentlyAddedAlbumRequest: null,
    recentlyAddedAlbumRequestKey: '',
    collectionAlbums: [],
    collectionAlbumsLoaded: false,
    collectionAlbumsLoading: false,
    collectionAlbumsLoadingPath: '',
    collectionAlbumsFetchId: 0,
    collectionFolders: [],
    collectionFoldersLoaded: false,
    collectionFoldersLoading: false,
    collectionFoldersError: '',
    collectionFoldersFetchId: 0,
    collectionNameOptions: [],
    collectionNameOptionsLoaded: false,
    collectionNameOptionsLoading: false,
    collectionNameOptionsRequest: null,
    selectedCollectionFolderPath: '',
    wishlistAlbums: [],
    wishlistAlbumsLoaded: false,
    wishlistFetchId: 0,
    searchTerm: '',
    searchInputValue: '',
    searchFocusNonce: 0,
    alphabetFilter: 'all',
    mediaTypeFilters: new Set(),
    folderFilters: new Set(),
    browseView: 'home',
    route: { view: 'home', albumId: null },
    currentTrackId: null,
    queueIds: [],
    shuffledQueueIds: [],
    shuffleActive: false,
    repeatMode: 'off',
    volume: 0.7,
    lastVolume: 0.7,
    queueOpen: false,
    fullscreenReturnHash: '',
    loginReturnHash: '',
    fullscreenLyricsHidden: true,
    fullscreenUiHidden: false,
    favoriteTrackIds: new Set(),
    favoriteAlbumIds: new Set(),
    albumShareCopiedAlbumId: '',
    downloadActivity: {
      phase: 'idle',
      target: '',
      label: '',
      detail: '',
      error: '',
    },
    libraryTab: 'albums',
    settingsTab: 'appearance',
    settingsStatusMessage: '',
    settings: { ...DEFAULT_SETTINGS },
    playbackTranscoding: { ffmpegAvailable: false, formats: ['original'] },
    currentUser: null,
    csrfToken: '',
    playlists: [],
    playlistsLoaded: false,
    playlistsLoading: false,
    playlistsError: '',
    selectedPlaylistId: '',
    selectedPlaylist: null,
    playlistDialogMode: 'create',
    playlistDialogTrackId: '',
    playlistDialogBusy: false,
    playlistDialogStatus: '',
    playlistDialogRenderKey: 0,
    canDownload: false,
    loginRouteOnly: false,
    pendingLibraryFolders: null,
    expandedFolderPaths: new Set(),
    artistInfoMap: new Map(),
    artistInfoLoading: new Set(),
    lyricsMap: new Map(),
    lyricsLoading: new Set(),
    lyricsRefreshRequestedIds: new Set(),
    tagEditorAlbumId: null,
    tagEditorMode: 'edit',
    tagEditorMusicBrainzId: '',
    tagEditorSuggestions: [],
    artistEditorName: '',
    collectionCoverName: '',
    lyricsEditorTrackId: '',
    lyricsSuggestions: [],
    visualizerActive: true,
    lyricsFrameId: 0,
    lastPlaybackPersistedAt: 0,
    audioContext: null,
    audioSource: null,
    analyser: null,
    analyserData: null,
    visualizerFrameId: 0,
    scanPollId: null,
    scanPollInFlight: false,
    searchFetchId: 0,
    unsearchedLibraryStale: false,
    artistFetchId: 0,
    widgetSettings: null,
    ambientCoverUrl: '',
    ambientCoverTitle: '',
    ambientCoverArtist: '',
    ambientCovers: [],
  };
}
