export const ICONS = {
  play: 'fa-play',
  pause: 'fa-pause',
  skipBack: 'fa-backward-step',
  skipForward: 'fa-forward-step',
  shuffle: 'fa-shuffle',
  repeat: 'fa-repeat',
  download: 'fa-download',
  volumeHigh: 'fa-volume-high',
  volumeMedium: 'fa-volume',
  volumeLow: 'fa-volume-low',
  volumeMuted: 'fa-volume-xmark',
  queue: 'fa-list',
  close: 'fa-xmark',
  back: 'fa-arrow-left',
  favorite: 'fa-heart',
  remove: 'fa-trash-can',
  clearQueue: 'fa-broom',
  drag: 'fa-grip-lines',
  edit: 'fa-pen-to-square',
  image: 'fa-image',
  search: 'fa-magnifying-glass',
  chevronRight: 'fa-chevron-right',
  chevronDown: 'fa-chevron-down',
  compactDisc: 'fa-compact-disc',
  fileAudio: 'fa-file-audio',
  recordVinyl: 'fa-record-vinyl',
  filter: 'fa-filter',
  addQueue: 'fa-plus',
};

export const PLAYER_ICONS = {
  download: '/assets/icons/player/download.svg',
  queue: '/assets/icons/player/list-ul.svg',
  remove: '/assets/icons/player/trash.svg',
  clearQueue: '/assets/icons/player/trash.svg',
  volumeHigh: '/assets/icons/player/volume-high.svg',
  volumeMedium: '/assets/icons/player/volume-medium.svg',
  volumeLow: '/assets/icons/player/volume-low.svg',
  volumeMuted: '/assets/icons/player/volume-xmark.svg',
};

export const REPEAT_MODES = ['off', 'all', 'one'];
export const MOBILE_SIDEBAR_QUERY = '(max-width: 720px)';

export const STORAGE_KEYS = {
  volume: 'Monochrome-Streamer-volume',
  favoriteTracks: 'Monochrome-Streamer-favorite-track-ids',
  favoriteAlbums: 'Monochrome-Streamer-favorite-album-ids',
  settings: 'Monochrome-Streamer-settings',
  playback: 'Monochrome-Streamer-playback-state',
  libraryFilters: 'Monochrome-Streamer-library-filters',
  downloadSettingsSync: 'Monochrome-Streamer-download-settings-sync',
  themeCookie: 'Monochrome-Streamer-theme',
};

export const DEFAULT_SETTINGS = {
  theme: 'black',
  fontPreset: 'jakarta',
  fontSize: 100,
  libraryPageSize: 50,
  customAccent: '#eb9200',
  themeBase: 'dark',
  customThemeBase: 'dark',
  libraryTitle: 'Monochrome-Streamer',
  showLibraryTitle: true,
  showHomeBanner: true,
  showRecentlyAdded: true,
  homeBannerEyebrow: 'Local Audio',
  homeBannerTitle: 'Your server, your collection, your rules.',
  homeBannerSubtitle: 'Browse your albums, open them like a proper detail page, and control playback from a full bottom player.',
  albumCoverBackground: true,
  dynamicColors: false,
  albumCardSize: 150,
  compactArtists: false,
  showHome: true,
  showLibrary: true,
  showFavorites: true,
  showFolderBrowser: false,
  sidebarCollapsed: false,
  closePanelsOnNavigation: true,
  nowPlayingClickAction: 'fullscreen',
  nowPlayingClickActionUserSet: false,
  appIconUrl: '',
  playerLayout: 'floating',
  showQualityInfo: true,
  gaplessPlayback: true,
  playbackQuality: 'original',
  downloadQuality: 'original',
  filenameTemplate: '{artist} - {title}',
  archiveFilenameTemplate: '{name}',
  zipEntryFolderTemplate: '{albumArtist}/{year} - {albumTitle}',
  bulkDownloadMethod: 'browser',
  includeCoverFile: false,
  generateM3u: false,
  generateJson: false,
  instanceUrl: '',
  devMode: false,
  cacheEnabled: true,
  autoUpdate: false,
};

export const NOW_PLAYING_CLICK_ACTIONS = new Set(['album', 'fullscreen', 'artist', 'none']);

export const LEGACY_SETTING_KEYS = [
  'scrobbleLocal',
  'scrobbleThreshold',
  'loveOnFavorite',
  'listenBrainzToken',
  'malojaUrl',
  'malojaApiKey',
  'replayGainMode',
  'monoAudio',
  'exponentialVolume',
  'playbackSpeed',
  'preservePitch',
];

export const SETTINGS_TABS = [
  ['appearance', 'Appearance'],
  ['interface', 'Interface'],
  ['audio', 'Audio'],
];

export const FONT_PRESETS = {
  jakarta: '"Plus Jakarta Sans", "Segoe UI", sans-serif',
  inter: 'Inter, "Plus Jakarta Sans", sans-serif',
  system: '"Segoe UI", "Helvetica Neue", Arial, sans-serif',
  mono: '"IBM Plex Mono", "Cascadia Mono", Consolas, monospace',
  serif: 'Georgia, "Times New Roman", serif',
  caviar: '"Monochrome Caviar Dreams", "Plus Jakarta Sans", sans-serif',
  'google-sans': '"Monochrome Google Sans Flex", "Plus Jakarta Sans", sans-serif',
  gotham: '"Monochrome Gotham", "Plus Jakarta Sans", sans-serif',
  helvetica: '"Monochrome Helvetica Neue", "Helvetica Neue", Arial, sans-serif',
  kaushan: '"Monochrome Kaushan Script", "Plus Jakarta Sans", cursive',
  metropolis: '"Monochrome Metropolis", "Plus Jakarta Sans", sans-serif',
  montserrat: '"Monochrome Montserrat", "Plus Jakarta Sans", sans-serif',
  'open-sans': '"Monochrome Open Sans", "Plus Jakarta Sans", sans-serif',
  quiapo: '"Monochrome Quiapo", "Plus Jakarta Sans", sans-serif',
  roboto: '"Monochrome Roboto", "Plus Jakarta Sans", sans-serif',
  trueno: '"Monochrome Trueno", "Plus Jakarta Sans", sans-serif',
  ubuntu: '"Monochrome Ubuntu", "Plus Jakarta Sans", sans-serif',
};

export const FONT_OPTIONS = [
  ['jakarta', 'Plus Jakarta Sans'],
  ['inter', 'Inter'],
  ['system', 'System UI'],
  ['mono', 'Monospace'],
  ['serif', 'Serif'],
  ['caviar', 'Caviar Dreams'],
  ['google-sans', 'Google Sans Flex'],
  ['gotham', 'Gotham'],
  ['helvetica', 'Helvetica Neue'],
  ['kaushan', 'Kaushan Script'],
  ['metropolis', 'Metropolis'],
  ['montserrat', 'Montserrat'],
  ['open-sans', 'Open Sans'],
  ['quiapo', 'Quiapo'],
  ['roboto', 'Roboto'],
  ['trueno', 'Trueno'],
  ['ubuntu', 'Ubuntu'],
];

export const THEME_BASE_OPTIONS = [
  ['dark', 'Dark'],
  ['light', 'Light'],
];

export const THEME_PRESETS = {
  system: {
    background: '#090909',
    surface: 'rgba(15, 15, 15, 0.78)',
    surface2: 'rgba(20, 20, 20, 0.94)',
    text: '#f4f4f0',
    muted: 'rgba(244, 244, 240, 0.65)',
    accent: '#eb9200',
    bodyTop: '#1c120d',
    bodyMid: '#090909',
    bodyBottom: '#050505',
  },
  black: {
    background: '#050505',
    surface: 'rgba(12, 12, 12, 0.82)',
    surface2: 'rgba(15, 15, 15, 0.96)',
    text: '#f7f7f2',
    muted: 'rgba(247, 247, 242, 0.64)',
    accent: '#eb9200',
    bodyTop: '#19100a',
    bodyMid: '#070707',
    bodyBottom: '#030303',
  },
  white: {
    background: '#f6f2ea',
    surface: 'rgba(255, 255, 255, 0.78)',
    surface2: 'rgba(248, 244, 235, 0.96)',
    text: '#17130f',
    muted: 'rgba(23, 19, 15, 0.64)',
    accent: '#bc5b00',
    bodyTop: '#fff9ef',
    bodyMid: '#f0e8dc',
    bodyBottom: '#ded5c8',
  },
  dark: {
    background: '#0b0d10',
    surface: 'rgba(18, 21, 25, 0.82)',
    surface2: 'rgba(18, 21, 25, 0.96)',
    text: '#eef2f5',
    muted: 'rgba(238, 242, 245, 0.64)',
    accent: '#8fb4ff',
    bodyTop: '#111822',
    bodyMid: '#090b0f',
    bodyBottom: '#050608',
  },
  ocean: {
    background: '#061115',
    surface: 'rgba(8, 25, 31, 0.82)',
    surface2: 'rgba(9, 31, 38, 0.96)',
    text: '#edfafa',
    muted: 'rgba(237, 250, 250, 0.66)',
    accent: '#18c2c8',
    bodyTop: '#082630',
    bodyMid: '#061115',
    bodyBottom: '#020809',
  },
  purple: {
    background: '#110b16',
    surface: 'rgba(25, 16, 32, 0.82)',
    surface2: 'rgba(30, 18, 40, 0.96)',
    text: '#fbf3ff',
    muted: 'rgba(251, 243, 255, 0.64)',
    accent: '#be8cff',
    bodyTop: '#271333',
    bodyMid: '#110b16',
    bodyBottom: '#07040a',
  },
  forest: {
    background: '#07100b',
    surface: 'rgba(12, 28, 18, 0.82)',
    surface2: 'rgba(13, 34, 21, 0.96)',
    text: '#f2fbf4',
    muted: 'rgba(242, 251, 244, 0.64)',
    accent: '#71cf72',
    bodyTop: '#132a18',
    bodyMid: '#07100b',
    bodyBottom: '#030704',
  },
  mocha: {
    background: '#110d0a',
    surface: 'rgba(30, 22, 16, 0.82)',
    surface2: 'rgba(35, 26, 19, 0.96)',
    text: '#fff4e8',
    muted: 'rgba(255, 244, 232, 0.64)',
    accent: '#d39b64',
    bodyTop: '#2d2118',
    bodyMid: '#110d0a',
    bodyBottom: '#070504',
  },
  macchiato: {
    background: '#14151d',
    surface: 'rgba(29, 31, 43, 0.82)',
    surface2: 'rgba(36, 39, 54, 0.96)',
    text: '#f4f0ff',
    muted: 'rgba(244, 240, 255, 0.64)',
    accent: '#f5a97f',
    bodyTop: '#25283a',
    bodyMid: '#14151d',
    bodyBottom: '#08090d',
  },
  frappe: {
    background: '#171922',
    surface: 'rgba(34, 38, 52, 0.82)',
    surface2: 'rgba(41, 45, 62, 0.96)',
    text: '#f2f0fa',
    muted: 'rgba(242, 240, 250, 0.64)',
    accent: '#e5c890',
    bodyTop: '#2b3042',
    bodyMid: '#171922',
    bodyBottom: '#0a0b10',
  },
  latte: {
    background: '#eff1f5',
    surface: 'rgba(255, 255, 255, 0.8)',
    surface2: 'rgba(230, 233, 239, 0.96)',
    text: '#1e1e2e',
    muted: 'rgba(30, 30, 46, 0.64)',
    accent: '#fe640b',
    bodyTop: '#f8f2e7',
    bodyMid: '#eff1f5',
    bodyBottom: '#dce0e8',
  },
};

export const PALETTE_THEMES = {
  butterGreen: {
    label: 'Butter / Green',
    light: '#ffefb3',
    dark: '#013e37',
  },
  creamCherry: {
    label: 'Cream / Cherry',
    light: '#efe6dd',
    dark: '#9a0002',
  },
  aureolinBistre: {
    label: 'Aureolin / Bistre',
    light: '#fbe311',
    dark: '#261606',
  },
  limeVibrant: {
    label: 'Lime / Vibrant',
    light: '#d3f00a',
    dark: '#f9100c',
  },
  violetImperial: {
    label: 'Violet / Imperial',
    light: '#f15153',
    dark: '#321847',
  },
  chartreuseGunmetal: {
    label: 'Chartreuse / Gunmetal',
    light: '#e1ff51',
    dark: '#00272c',
  },
  maroonXanthous: {
    label: 'Maroon / Xanthous',
    light: '#f7b638',
    dark: '#780115',
  },
  buttermilkBlue: {
    label: 'Buttermilk / Blue',
    light: '#fff2bd',
    dark: '#285ccc',
  },
  lavenderVelvet: {
    label: 'Lavender / Velvet',
    light: '#d3c5f6',
    dark: '#3b2a60',
  },
  salmonGreen: {
    label: 'Salmon / Green',
    light: '#ff947a',
    dark: '#025259',
  },
};

export const MEDIA_TYPE_ICONS = {
  CD: '/assets/icons/media-type/compact-disc.svg',
  'Digital Media': '/assets/icons/media-type/file-waveform.svg',
  Vinyl: '/assets/icons/media-type/record-vinyl.svg',
  'Cassette Tape': '/assets/icons/media-type/cassette-tape.svg',
};

export const MEDIA_TYPE_FILTERS = ['all', ...Object.keys(MEDIA_TYPE_ICONS)];

export const RENDER_LIMITS = {
  albums: 180,
  artists: 180,
  tracks: 240,
  queue: 220,
  folders: 160,
};

export const ALPHABET_FILTERS = ['all', '#', ...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('')];
